{{- range $index, $runner := .Values.runners }}
{{- if or $runner.registrationToken $runner.runnerToken}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-runner.fullname" $ }}-{{ $index }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ include "gitlab-runner.fullname" $ }}
    chart: {{ include "gitlab-runner.chart" $ }}
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  runner-registration-token-{{ $index }}: {{ default "" $runner.registrationToken | b64enc | quote }}
  runner-token-{{ $index }}: {{ default "" $runner.runnerToken | b64enc | quote }}
{{- end}}
{{- end}}
